[phases.setup]
# نكتفي بتعريف بايثون وقاعدة البيانات
nixPkgs = ["python311", "postgresql"]

[phases.install]
# نستخدم pip مباشرة لتثبيت المكتبات دون محاولة إنشاء venv يدوياً
cmds = ["pip install -r requirements.txt"]

[start]
# أمر التشغيل المباشر
cmd = "gunicorn -b 0.0.0.0:8080 run:app"
